/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroQuote?: string;
  heroQuoteAttribution?: string;
  bookingAgentName?: string;
  bookingAgentEmail?: string;
  bookingAgentPhone?: string;
  socialLinks?: Array<{
    platform?:
      | "YouTube"
      | "Facebook"
      | "Instagram"
      | "SoundCloud"
      | "Twitter"
      | "Spotify";
    url?: string;
    _key: string;
  }>;
  spotifyEmbedUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  credit?: string;
  order?: number;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youtubeId?: string;
  description?: string;
  order?: number;
  featured?: boolean;
};

export type PressQuote = {
  _id: string;
  _type: "pressQuote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  publication?: string;
  publicationUrl?: string;
  year?: number;
  order?: number;
};

export type Album = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  releaseYear?: number;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  albumType?: "album" | "ep" | "single";
  description?: string;
  tracklist?: Array<{
    trackNumber?: number;
    title?: string;
    _key: string;
  }>;
  credits?: string;
  buyLinks?: Array<{
    platform?:
      | "Spotify"
      | "Apple Music"
      | "iTunes"
      | "Amazon"
      | "Bandcamp"
      | "PayPal CD";
    url?: string;
    _key: string;
  }>;
  pressQuotes?: Array<{
    quote?: string;
    attribution?: string;
    publication?: string;
    publicationUrl?: string;
    _key: string;
  }>;
  order?: number;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Musician = {
  _id: string;
  _type: "musician";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  order?: number;
  isCurrentMember?: boolean;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueAddress?: string;
  city?: string;
  state?: string;
  startTime?: string;
  phone?: string;
  notes?: string;
  ticketUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | Photo
  | SanityImageCrop
  | SanityImageHotspot
  | Video
  | PressQuote
  | Album
  | Slug
  | Musician
  | Show
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/queries.ts
// Variable: upcomingShowsQuery
// Query: *[_type == "show" && date >= now()] | order(date asc) [0...$limit]
export type UpcomingShowsQueryResult = Array<{
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueAddress?: string;
  city?: string;
  state?: string;
  startTime?: string;
  phone?: string;
  notes?: string;
  ticketUrl?: string;
}>;

// Source: src/lib/queries.ts
// Variable: allShowsQuery
// Query: *[_type == "show"] | order(date asc)
export type AllShowsQueryResult = Array<{
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueAddress?: string;
  city?: string;
  state?: string;
  startTime?: string;
  phone?: string;
  notes?: string;
  ticketUrl?: string;
}>;

// Source: src/lib/queries.ts
// Variable: allMusiciansQuery
// Query: *[_type == "musician"] | order(isCurrentMember desc, order asc) {    _id,    name,    role,    bio,    isCurrentMember,    order,    photo {      asset -> {        _id,        url      }    }  }
export type AllMusiciansQueryResult = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  isCurrentMember: boolean | null;
  order: number | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: src/lib/queries.ts
// Variable: allAlbumsQuery
// Query: *[_type == "album"] | order(featured desc, order asc)
export type AllAlbumsQueryResult = Array<{
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  releaseYear?: number;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  albumType?: "album" | "ep" | "single";
  description?: string;
  tracklist?: Array<{
    trackNumber?: number;
    title?: string;
    _key: string;
  }>;
  credits?: string;
  buyLinks?: Array<{
    platform?:
      | "Amazon"
      | "Apple Music"
      | "Bandcamp"
      | "iTunes"
      | "PayPal CD"
      | "Spotify";
    url?: string;
    _key: string;
  }>;
  pressQuotes?: Array<{
    quote?: string;
    attribution?: string;
    publication?: string;
    publicationUrl?: string;
    _key: string;
  }>;
  order?: number;
  featured?: boolean;
}>;

// Source: src/lib/queries.ts
// Variable: albumBySlugQuery
// Query: *[_type == "album" && slug.current == $slug][0] {    ...,    pressQuotes[]  }
export type AlbumBySlugQueryResult = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  releaseYear?: number;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  albumType?: "album" | "ep" | "single";
  description?: string;
  tracklist?: Array<{
    trackNumber?: number;
    title?: string;
    _key: string;
  }>;
  credits?: string;
  buyLinks?: Array<{
    platform?:
      | "Amazon"
      | "Apple Music"
      | "Bandcamp"
      | "iTunes"
      | "PayPal CD"
      | "Spotify";
    url?: string;
    _key: string;
  }>;
  pressQuotes: Array<{
    quote?: string;
    attribution?: string;
    publication?: string;
    publicationUrl?: string;
    _key: string;
  }> | null;
  order?: number;
  featured?: boolean;
} | null;

// Source: src/lib/queries.ts
// Variable: allPressQuotesQuery
// Query: *[_type == "pressQuote"] | order(order asc)
export type AllPressQuotesQueryResult = Array<{
  _id: string;
  _type: "pressQuote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  publication?: string;
  publicationUrl?: string;
  year?: number;
  order?: number;
}>;

// Source: src/lib/queries.ts
// Variable: allVideosQuery
// Query: *[_type == "video"] | order(featured desc, order asc)
export type AllVideosQueryResult = Array<{
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youtubeId?: string;
  description?: string;
  order?: number;
  featured?: boolean;
}>;

// Source: src/lib/queries.ts
// Variable: allPhotosQuery
// Query: *[_type == "photo"] | order(order asc)
export type AllPhotosQueryResult = Array<{
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  credit?: string;
  order?: number;
  featured?: boolean;
}>;

// Source: src/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]
export type SiteSettingsQueryResult = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroQuote?: string;
  heroQuoteAttribution?: string;
  bookingAgentName?: string;
  bookingAgentEmail?: string;
  bookingAgentPhone?: string;
  socialLinks?: Array<{
    platform?:
      | "Facebook"
      | "Instagram"
      | "SoundCloud"
      | "Spotify"
      | "Twitter"
      | "YouTube";
    url?: string;
    _key: string;
  }>;
  spotifyEmbedUrl?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "show" && date >= now()] | order(date asc) [0...$limit]\n': UpcomingShowsQueryResult;
    '\n  *[_type == "show"] | order(date asc)\n': AllShowsQueryResult;
    '\n  *[_type == "musician"] | order(isCurrentMember desc, order asc) {\n    _id,\n    name,\n    role,\n    bio,\n    isCurrentMember,\n    order,\n    photo {\n      asset -> {\n        _id,\n        url\n      }\n    }\n  }\n': AllMusiciansQueryResult;
    '\n  *[_type == "album"] | order(featured desc, order asc)\n': AllAlbumsQueryResult;
    '\n  *[_type == "album" && slug.current == $slug][0] {\n    ...,\n    pressQuotes[]\n  }\n': AlbumBySlugQueryResult;
    '\n  *[_type == "pressQuote"] | order(order asc)\n': AllPressQuotesQueryResult;
    '\n  *[_type == "video"] | order(featured desc, order asc)\n': AllVideosQueryResult;
    '\n  *[_type == "photo"] | order(order asc)\n': AllPhotosQueryResult;
    '\n  *[_type == "siteSettings"][0]\n': SiteSettingsQueryResult;
  }
}
