/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroQuote?: string;
  heroQuoteAttribution?: string;
  bookingAgentName?: string;
  bookingAgentEmail?: string;
  bookingAgentPhone?: string;
  socialLinks?: Array<{
    platform?:
      | "YouTube"
      | "Facebook"
      | "Instagram"
      | "SoundCloud"
      | "Twitter"
      | "Spotify";
    url?: string;
    _key: string;
  }>;
  spotifyEmbedUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  credit?: string;
  order?: number;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youtubeId?: string;
  description?: string;
  order?: number;
  featured?: boolean;
};

export type PressQuote = {
  _id: string;
  _type: "pressQuote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  publication?: string;
  publicationUrl?: string;
  year?: number;
  order?: number;
};

export type Album = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  releaseYear?: number;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  albumType?: "album" | "ep" | "single";
  description?: string;
  tracklist?: Array<{
    trackNumber?: number;
    title?: string;
    _key: string;
  }>;
  credits?: string;
  buyLinks?: Array<{
    platform?:
      | "Spotify"
      | "Apple Music"
      | "iTunes"
      | "Amazon"
      | "Bandcamp"
      | "PayPal CD";
    url?: string;
    _key: string;
  }>;
  pressQuotes?: Array<{
    quote?: string;
    attribution?: string;
    publication?: string;
    publicationUrl?: string;
    _key: string;
  }>;
  order?: number;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Musician = {
  _id: string;
  _type: "musician";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  order?: number;
  photoUrl?: string;
  isCurrentMember?: boolean;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueAddress?: string;
  city?: string;
  state?: string;
  startTime?: string;
  phone?: string;
  notes?: string;
  ticketUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | Photo
  | SanityImageCrop
  | SanityImageHotspot
  | Video
  | PressQuote
  | Album
  | Slug
  | Musician
  | Show
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/app/admin/albums/page.tsx
// Variable: albumsAdmin
// Query: *[_type == "album"] | order(order asc) { _id, title, releaseYear, albumType, order, featured }
export type AlbumsAdminResult = Array<{
  _id: string;
  title: string | null;
  releaseYear: number | null;
  albumType: "album" | "ep" | "single" | null;
  order: number | null;
  featured: boolean | null;
}>;

// Source: src/app/admin/musicians/page.tsx
// Variable: musiciansAdmin
// Query: *[_type == "musician"] | order(isCurrentMember desc, order asc) { _id, name, role, isCurrentMember, order }
export type MusiciansAdminResult = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  isCurrentMember: boolean | null;
  order: number | null;
}>;

// Source: src/app/admin/page.tsx
// Variable: countsQuery
// Query: {  "shows": count(*[_type == "show" && date >= now()]),  "albums": count(*[_type == "album"]),  "musicians": count(*[_type == "musician"]),  "press": count(*[_type == "pressQuote"]),  "photos": count(*[_type == "photo"]),  "videos": count(*[_type == "video"])}
export type CountsQueryResult = {
  shows: number;
  albums: number;
  musicians: number;
  press: number;
  photos: number;
  videos: number;
};

// Source: src/app/admin/page.tsx
// Variable: upcomingShowsQuery
// Query: *[_type == "show" && date >= now()] | order(date asc) [0...3] {    _id, date, venueName, city, state  }
export type UpcomingShowsQueryResult = Array<{
  _id: string;
  date: string | null;
  venueName: string | null;
  city: string | null;
  state: string | null;
}>;

// Source: src/app/admin/press/page.tsx
// Variable: pressAdmin
// Query: *[_type == "pressQuote"] | order(order asc) { _id, quote, attribution, order }
export type PressAdminResult = Array<{
  _id: string;
  quote: string | null;
  attribution: string | null;
  order: number | null;
}>;

// Source: src/app/admin/shows/[id]/page.tsx
// Variable: showByIdQuery
// Query: *[_type == "show" && _id == $id][0]
export type ShowByIdQueryResult = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  venueName?: string;
  venueAddress?: string;
  city?: string;
  state?: string;
  startTime?: string;
  phone?: string;
  notes?: string;
  ticketUrl?: string;
} | null;

// Source: src/app/admin/shows/page.tsx
// Variable: allShowsAdmin
// Query: *[_type == "show"] | order(date desc) {    _id, date, venueName, city, state  }
export type AllShowsAdminResult = Array<{
  _id: string;
  date: string | null;
  venueName: string | null;
  city: string | null;
  state: string | null;
}>;

// Source: src/app/admin/videos/page.tsx
// Variable: videosAdmin
// Query: *[_type == "video"] | order(featured desc, order asc) { _id, title, youtubeId, featured, order }
export type VideosAdminResult = Array<{
  _id: string;
  title: string | null;
  youtubeId: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "album"] | order(order asc) { _id, title, releaseYear, albumType, order, featured }': AlbumsAdminResult;
    '*[_type == "musician"] | order(isCurrentMember desc, order asc) { _id, name, role, isCurrentMember, order }': MusiciansAdminResult;
    '{\n  "shows": count(*[_type == "show" && date >= now()]),\n  "albums": count(*[_type == "album"]),\n  "musicians": count(*[_type == "musician"]),\n  "press": count(*[_type == "pressQuote"]),\n  "photos": count(*[_type == "photo"]),\n  "videos": count(*[_type == "video"])\n}': CountsQueryResult;
    '\n  *[_type == "show" && date >= now()] | order(date asc) [0...3] {\n    _id, date, venueName, city, state\n  }\n': UpcomingShowsQueryResult;
    '*[_type == "pressQuote"] | order(order asc) { _id, quote, attribution, order }': PressAdminResult;
    '*[_type == "show" && _id == $id][0]': ShowByIdQueryResult;
    '\n  *[_type == "show"] | order(date desc) {\n    _id, date, venueName, city, state\n  }\n': AllShowsAdminResult;
    '*[_type == "video"] | order(featured desc, order asc) { _id, title, youtubeId, featured, order }': VideosAdminResult;
  }
}
